/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import java.awt.HeadlessException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;
import puntoventa001.Conexion;
import puntoventa001.Main;
import puntoventa001.Procedimientos;

/**
 *
 * @author library_pc1
 */
public class EstadoCuenta extends javax.swing.JDialog {

    String idCliente = "";
    Procedimientos p = new Procedimientos();

    /**
     * Creates new form EstadoCuenta
     */
    public EstadoCuenta(java.awt.Frame parent, boolean modal, String id) {
        super(parent, modal);
        initComponents();
        idCliente = id;

       actualizarEstado();

    }

    public void actualizarEstado() {
        
        String[] detalles = p.getDetailsCliente(idCliente);
        jLabel26.setText(detalles[0]);
        jLabel28.setText("$" + detalles[4] + "0");
        System.out.println(detalles[3]);
        if (Double.parseDouble(detalles[3]) != 0.0) {
            jLabel29.setText("$" + detalles[3] + "0");
        } else {
            jLabel29.setText("- Sin Limite -");
        }
        ArrayList<String[]> ventas = p.getCuentas(idCliente);
        actualizarTabla(jTable2, ventas);
        if (Double.parseDouble(detalles[4]) == 0.0) {
            jButton3.setEnabled(false);
            jButton4.setEnabled(false);
        }
    }

    private void actualizarTabla(javax.swing.JTable t, ArrayList<String[]> listaT) {
        this.LimpiarJTable(t);
        ArrayList<String> row = new ArrayList<String>();
        for (String[] prod : listaT) {
            for (String string : prod) {
                row.add(string);
            }
            ((DefaultTableModel) t.getModel()).addRow(row.toArray());
            row = new ArrayList<String>();
        }
    }

    private void actualizarTabla1(javax.swing.JTable t, ArrayList<String[]> listaT) {
        this.LimpiarJTable(t);
        ArrayList<String> row = new ArrayList<String>();
        for (String[] prod : listaT) {

            row.add(prod[2]);
            row.add(prod[11]);
            row.add(prod[1]);
            row.add(prod[3]);

            ((DefaultTableModel) t.getModel()).addRow(row.toArray());
            row = new ArrayList<String>();
        }
    }

    public void LimpiarJTable(javax.swing.JTable t) {
        DefaultTableModel mode = (DefaultTableModel) t.getModel();
        int rango = mode.getRowCount() - 1;
        for (int i = rango; i >= 0; i--) {

            mode.removeRow(i);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Estado de cuenta");

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(153, 51, 0));
        jLabel26.setText("Nombre de cliente");

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(204, 51, 0));
        jLabel27.setText("Saldo actual");

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(153, 51, 0));
        jLabel28.setText("Saldo actual");

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(153, 51, 0));
        jLabel29.setText("- Sin Limite -");

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(204, 51, 0));
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel30.setText("Limite de credito:");

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/gold.gif"))); // NOI18N
        jButton3.setText("Abonar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/money.gif"))); // NOI18N
        jButton4.setText("Liquidar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Articulo", "Precio venta", "Cantidad", "Monto"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);
        jTable1.getColumnModel().getColumn(0).setResizable(false);
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(100);
        jTable1.getColumnModel().getColumn(1).setResizable(false);
        jTable1.getColumnModel().getColumn(2).setResizable(false);
        jTable1.getColumnModel().getColumn(3).setResizable(false);

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(204, 51, 0));
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel31.setText("Total:");

        jLabel32.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(153, 51, 0));
        jLabel32.setText("$0.00");

        jButton6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/icon-cancel.png"))); // NOI18N
        jButton6.setText("Cerrar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "FOLIO", "Fecha"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable2);
        jTable2.getColumnModel().getColumn(0).setResizable(false);
        jTable2.getColumnModel().getColumn(0).setPreferredWidth(4);

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(204, 51, 0));
        jLabel33.setText("Ventas");

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(204, 51, 0));
        jLabel34.setText("Detalles");

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/AdminPdf.gif"))); // NOI18N
        jButton7.setText("Estado de cuenta");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/add.gif"))); // NOI18N
        jButton5.setText("Agregar Saldo");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel32))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 658, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel33)
                                .addGap(126, 126, 126)
                                .addComponent(jLabel34))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton7)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton7)
                    .addComponent(jButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(jLabel34))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel31)
                            .addComponent(jLabel32)
                            .addComponent(jButton6)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 266, Short.MAX_VALUE)
                        .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel29))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(4, 4, 4)
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(jLabel28)
                    .addComponent(jLabel30)
                    .addComponent(jLabel29))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        actualizarTabla1(jTable1, p.getDetailsCompra(jTable2.getValueAt(jTable2.getSelectedRow(), 0).toString()));
        double suma = 0.0;
        for (int i = 0; i < jTable1.getRowCount(); i++) {
            suma += Double.parseDouble(jTable1.getValueAt(i, 3).toString());
        }
        jLabel32.setText("$" + suma + "0");
    }//GEN-LAST:event_jTable2MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            double abono = Double.parseDouble(javax.swing.JOptionPane.showInputDialog("¿Cuanto abonò: ?"));
            String[] detalles = p.getDetailsCliente(idCliente);
            double saldo = Double.parseDouble(detalles[4]);
            System.out.println("" + saldo);
            if (abono == saldo) {
                int opc = JOptionPane.showConfirmDialog(null, "Esta seguro de liquidar por completo el adeudo", "Liquidar", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                if (opc == JOptionPane.YES_OPTION) {
                    p.liquidar(idCliente, Double.parseDouble(detalles[4]));
                    p.liquidar(idCliente);
                    p.agregarCuenta("-" + abono, "LIQUIDACIÓN DE COMPRA", puntoventa001.Main.interfaz.usuario, idCliente);
                    detalles = p.getDetailsCliente(idCliente);
                    jLabel26.setText(detalles[0]);
                    jLabel28.setText("$" + detalles[4] + "0");
                    System.out.println(detalles[3]);
                    if (Double.parseDouble(detalles[3]) != 0.0) {
                        jLabel29.setText("$" + detalles[3] + "0");
                    } else {
                        jLabel29.setText("- Sin Limite -");
                    }
                    ArrayList<String[]> ventas = p.getCuentas(idCliente);
                    actualizarTabla(jTable2, ventas);
                    if (Double.parseDouble(detalles[4]) == 0.0) {
                        jButton3.setEnabled(false);
                        jButton4.setEnabled(false);
                    }
                    LimpiarJTable(jTable1);
                }
            }
            if (abono > saldo) {
                javax.swing.JOptionPane.showMessageDialog(null, "El abono es mayor al adeudo ", "ERROR", 0);
            }
            if (abono < saldo) {
                p.liquidar(idCliente, abono);
                p.agregarCuenta("-" + abono, "ABONO", puntoventa001.Main.interfaz.usuario, idCliente);
                detalles = p.getDetailsCliente(idCliente);
                jLabel26.setText(detalles[0]);
                jLabel28.setText("$" + detalles[4] + "0");
                System.out.println(detalles[3]);
                if (Double.parseDouble(detalles[3]) != 0.0) {
                    jLabel29.setText("$" + detalles[3] + "0");
                } else {
                    jLabel29.setText("- Sin Limite -");
                }
                ArrayList<String[]> ventas = p.getCuentas(idCliente);
                actualizarTabla(jTable2, ventas);
                if (Double.parseDouble(detalles[4]) == 0.0) {
                    jButton3.setEnabled(false);
                    jButton4.setEnabled(false);
                }
            }
        } catch (HeadlessException headlessException) {
        } catch (NumberFormatException numberFormatException) {
            numberFormatException.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(null, "Debes dar valores numericos", "ERROR", 0);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int opc = JOptionPane.showConfirmDialog(null, "Esta seguro de liquidar por completo el adeudo", "Liquidar", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (opc == JOptionPane.YES_OPTION) {

            String[] detalles = p.getDetailsCliente(idCliente);
            double saldo = Double.parseDouble(detalles[4]);
            p.liquidar(idCliente, saldo);
            p.liquidar(idCliente);
            p.agregarCuenta("-" + saldo, "LIQUIDACIÓN DE COMPRA", puntoventa001.Main.interfaz.usuario, idCliente);
            detalles = p.getDetailsCliente(idCliente);
            jLabel26.setText(detalles[0]);
            jLabel28.setText("$" + detalles[4] + "0");
            System.out.println(detalles[3]);
            if (Double.parseDouble(detalles[3]) != 0.0) {
                jLabel29.setText("$" + detalles[3] + "0");
            } else {
                jLabel29.setText("- Sin Limite -");
            }
            ArrayList<String[]> ventas = p.getCuentas(idCliente);
            actualizarTabla(jTable2, ventas);
            if (Double.parseDouble(detalles[4]) == 0.0) {
                jButton3.setEnabled(false);
                jButton4.setEnabled(false);
            }
            LimpiarJTable(jTable1);
        }
    }//GEN-LAST:event_jButton4ActionPerformed
    private Procedimientos procedimiento = new Procedimientos();
    private Conexion conexion = new Conexion();
    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed

        JasperReport jasperReport;
        JasperPrint jasperPrint;
        String[] tiket = procedimiento.getDetailsTiket();
        String titulo = tiket[0], subtitulo = tiket[1], fina = tiket[2];
        try {
            jasperReport = JasperCompileManager.compileReport("EstadoCuenta.jrxml");
            //se procesa el archivo jasper
            Map parametro1 = new HashMap();
            parametro1.put("id", this.idCliente);

            jasperPrint = JasperFillManager.fillReport(jasperReport, parametro1, conexion.con);
            //impresion de reporte
            // TRUE: muestra la ventana de dialogo "preferencias de impresion"
            JasperViewer jp = new JasperViewer(jasperPrint);
            jp.setTitle("Estado de cuenta");
            jp.setIconImage(Main.interfaz.getIconImage());
            jp.setVisible(true);
            jp.setAlwaysOnTop(true);

        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(null, ex.getMessage());

        }


    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        try {
            double saldo = Double.parseDouble(JOptionPane.showInputDialog("Cantidad de saldo a agregar: "));
            p.agregar(idCliente, saldo);
            actualizarEstado();
        } catch (HeadlessException headlessException) {
        } catch (NumberFormatException numberFormatException) {
            javax.swing.JOptionPane.showMessageDialog(null, "Debes de insertar solo numeros ", "ERROR", 0);
        }
    }//GEN-LAST:event_jButton5ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
