/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import java.awt.event.KeyEvent;
import java.math.BigDecimal;
import java.math.RoundingMode;

/**
 *
 * @author library_pc1
 */
public class Ganel extends javax.swing.JDialog {

    /**
     * Creates new form Ganel
     */
    String datosD[] = null;

    public Ganel(java.awt.Frame parent, boolean modal, String[] datos) {
        super(parent, modal);
        initComponents();
        if (datos != null) {
            nombre.setText(datos[1]);
            importe.setText(datos[2]);
            unidad.setText("Precio por unidad = " + datos[2]);
            precio = Double.parseDouble(datos[2]);
        } else {
        }
    }

    public void setDatosD(String[] datosD) {

        this.datosD = datosD;
        nombre.setText(datosD[1]);
        importe.setText(datosD[2]);
        unidad.setText("Precio por unidad = " + datosD[2]);
        precio = Double.parseDouble(datosD[2]);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        nombre = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        unidad = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        importe = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/icon-cancel.png"))); // NOI18N
        jButton3.setText("Cancelar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/icon-valid.png"))); // NOI18N
        jButton4.setText("Guardar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        nombre.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        nombre.setForeground(new java.awt.Color(153, 51, 0));
        nombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombre.setText("Producto");

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(153, 51, 0));
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("Cantidad actual");

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(153, 51, 0));
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("Importe actual");

        unidad.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        unidad.setForeground(new java.awt.Color(153, 51, 0));
        unidad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        unidad.setText("Precio por unidad = ");

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTextField1.setText("1.00");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField1FocusLost(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });

        importe.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        importe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importeActionPerformed(evt);
            }
        });
        importe.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                importeFocusLost(evt);
            }
        });
        importe.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                importeKeyPressed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/icon-cancel.png"))); // NOI18N
        jButton5.setText("Cancelar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/icon-valid.png"))); // NOI18N
        jButton6.setText("Guardar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(unidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel27, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(importe))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(jButton6)
                .addGap(41, 41, 41)
                .addComponent(jButton5)
                .addContainerGap(140, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nombre)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(jLabel28))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(importe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(unidad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(jButton5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

        ok();

    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        try {
            String val = precio * Double.parseDouble(jTextField1.getText()) + "";
            BigDecimal big = new BigDecimal(val);
            big = big.setScale(1, RoundingMode.HALF_UP);
            importe.setText(big + "0");
            String val2 = Double.parseDouble(importe.getText()) / precio + "";
            BigDecimal big2 = new BigDecimal(val2);
            big2 = big2.setScale(3, RoundingMode.HALF_UP);
            jTextField1.setText("" + big2);
        } catch (NumberFormatException numberFormatException) {
        }
        ok();
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void importeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importeActionPerformed
        try {

            String val = Double.parseDouble(importe.getText()) / precio + "";
            BigDecimal big = new BigDecimal(val);
            big = big.setScale(3, RoundingMode.HALF_UP);
            jTextField1.setText("" + big);
            String val2 = precio * Double.parseDouble(jTextField1.getText()) + "";
            BigDecimal big2 = new BigDecimal(val2);
            big = big.setScale(1, RoundingMode.HALF_UP);
            importe.setText(big2 + "0");
        } catch (NumberFormatException numberFormatException) {
        }
        ok();
    }//GEN-LAST:event_importeActionPerformed

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            setVisible(false);
        }
        try {
            String val = precio * Double.parseDouble(jTextField1.getText()) + "";
            BigDecimal big = new BigDecimal(val);
            big = big.setScale(1, RoundingMode.HALF_UP);
            importe.setText(big + "0");
            
        } catch (NumberFormatException numberFormatException) {
        }
    }//GEN-LAST:event_jTextField1KeyPressed

    private void importeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_importeKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            setVisible(false);
        }
        try {
            String val = Double.parseDouble(importe.getText()) / precio + "";
            BigDecimal big = new BigDecimal(val);
            big = big.setScale(3, RoundingMode.HALF_UP);
            jTextField1.setText("" + big);
            

        } catch (NumberFormatException numberFormatException) {
        }
    }//GEN-LAST:event_importeKeyPressed

    private void jTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusLost
        try {
            String val = precio * Double.parseDouble(jTextField1.getText()) + "";
            BigDecimal big = new BigDecimal(val);
            big = big.setScale(1, RoundingMode.HALF_UP);
            importe.setText(big + "0");
            
        } catch (NumberFormatException numberFormatException) {
        }
    }//GEN-LAST:event_jTextField1FocusLost

    private void importeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_importeFocusLost
        try {
            String val = Double.parseDouble(importe.getText()) / precio + "";
            BigDecimal big = new BigDecimal(val);
            big = big.setScale(3, RoundingMode.HALF_UP);
            jTextField1.setText("" + big);
            String val2 = precio * Double.parseDouble(jTextField1.getText()) + "";
            BigDecimal big2 = new BigDecimal(val2);
            big2 = big2.setScale(1, RoundingMode.HALF_UP);
            importe.setText(big2 + "0");
        } catch (NumberFormatException numberFormatException) {
        }
    }//GEN-LAST:event_importeFocusLost
    public void ok() {

        setCantidad(Double.parseDouble(jTextField1.getText()));
        setVisible(false);
    }
    double cantidad = 0.0;
    public double precio = 0.0;

    public double getCantidad() {
        return Double.parseDouble(jTextField1.getText());
    }

    public void setCantidad(double cantidad) {
        this.cantidad = cantidad;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField importe;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JTextField jTextField1;
    public javax.swing.JLabel nombre;
    public javax.swing.JLabel unidad;
    // End of variables declaration//GEN-END:variables
}
